---
name: "tagged-release"

on:
  push:
    tags:
      - "*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Vendor
        uses: actions-rs/cargo@v1
        with:
          command: vendor
      - name: Pack
        id: pack
        shell: bash
        run: |
          TAG=`git describe --tags --abbrev=0`
          mkdir -p .cargo
          cp vendor.toml .cargo/config.toml
          7z a ../whisper-$TAG.zip
          cp ../whisper-$TAG.zip ./
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.zip
